/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package strata.themrdt.org/dev/middleware/cmd/cgoexport */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "cexport.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// strataInit initializes the global client. Must be called once before any other strata_* function.
//
extern void strataInit(char* baseURL);

// strataSetToken sets the JWT access token.
//
extern void strataSetToken(char* token);

// strataSetRefreshToken sets the refresh token.
//
extern void strataSetRefreshToken(char* token);

// strataGetToken returns the current access token. Caller must free with strataFree().
//
extern char* strataGetToken();

// strataGetRefreshToken returns the current refresh token. Caller must free with strataFree().
//
extern char* strataGetRefreshToken();

// strataFree frees a string or buffer returned by any strata_* function.
//
extern void strataFree(char* ptr);

// strataLastError returns the last error message. Returns NULL if no error. Caller must free.
//
extern char* strataLastError();

// strataHealth calls GET /health.
//
extern char* strataHealth();

// strataRegister creates a new user account.
//
extern char* strataRegister(char* username, char* email, char* password);

// strataLogin authenticates and stores tokens. Returns JSON TokenPair.
//
extern char* strataLogin(char* username, char* password);

// strataRefresh exchanges a refresh token for a new token pair.
//
extern char* strataRefresh(char* refreshToken);

// strataLogout clears tokens and calls POST /auth/logout.
//
extern char* strataLogout();

// strataProjectCreate creates a new project.
//
extern char* strataProjectCreate(char* name, char* description);

// strataProjectList lists all projects for the authenticated user.
//
extern char* strataProjectList();

// strataProjectGet fetches a single project by ID.
//
extern char* strataProjectGet(char* projectID);

// strataProjectDelete deletes a project.
//
extern char* strataProjectDelete(char* projectID);

// strataPushCheckChunks checks which hashes already exist on the server.
// hashesJSON: JSON array string e.g. '["abc123","def456"]'
//
extern char* strataPushCheckChunks(char* projectID, char* hashesJSON);

// strataPushUploadChunk uploads raw chunk bytes. Returns 1 on success, 0 on error.
//
extern int strataPushUploadChunk(char* projectID, char* hash, void* data, int dataLen);

// strataPushCommit finalizes a push. bodyJSON is a JSON-encoded CommitRequest.
//
extern char* strataPushCommit(char* projectID, char* bodyJSON);

// strataPullDiff computes the diff between two commits. bodyJSON is a JSON-encoded DiffRequest.
//
extern char* strataPullDiff(char* projectID, char* bodyJSON);

// strataPullDownloadChunk downloads a chunk's raw bytes.
// outLen is set to the byte count. Returns a malloc'd pointer — free with strataFree().
//
extern void* strataPullDownloadChunk(char* projectID, char* hash, int* outLen);

// strataListRefs lists all refs for a project.
//
extern char* strataListRefs(char* projectID);

// strataListCommits lists commits with pagination.
//
extern char* strataListCommits(char* projectID, int limit, int offset);

// strataGetCommit fetches a single commit.
//
extern char* strataGetCommit(char* projectID, char* commitID);

// strataListCommitFiles lists all files in a commit.
//
extern char* strataListCommitFiles(char* projectID, char* commitID);

// strataGetTree fetches the file tree for a project at a given ref.
//
extern char* strataGetTree(char* projectID, char* ref);

// strataCreateBranch creates a new branch from an existing ref.
//
extern char* strataCreateBranch(char* projectID, char* name, char* fromRef);

// strataMergeAnalyze analyzes whether two branches can be merged.
//
extern char* strataMergeAnalyze(char* projectID, char* sourceBranch, char* targetBranch);

// strataMergeExecute executes a merge. bodyJSON is a JSON-encoded MergeExecuteRequest.
//
extern char* strataMergeExecute(char* projectID, char* bodyJSON);

// strataLockList lists all active locks for a project.
//
extern char* strataLockList(char* projectID);

// strataLockAcquire acquires an advisory lock on a file path.
//
extern char* strataLockAcquire(char* projectID, char* filePath, char* branch);

// strataLockRelease releases a lock. force=1 overrides another user's lock.
//
extern char* strataLockRelease(char* projectID, char* filePath, int force);

#ifdef __cplusplus
}
#endif
